class CreateProducts < ActiveRecord::Migration[8.0]
  def change
    create_table :products do |t|
      t.string :code
      t.text :url
      t.string :creator
      t.bigint :created_t
      t.datetime :created_datetime
      t.bigint :last_modified_t
      t.datetime :last_modified_datetime
      t.string :product_name
      t.string :generic_name
      t.string :quantity
      t.text :packaging
      t.text :packaging_tags
      t.text :brands
      t.text :brands_tags
      t.text :categories
      t.text :categories_tags
      t.text :categories_fr
      t.text :origins
      t.text :origins_tags
      t.text :manufacturing_places
      t.text :manufacturing_places_tags
      t.text :labels
      t.text :labels_tags
      t.text :labels_fr
      t.text :emb_codes
      t.text :emb_codes_tags
      t.string :first_packaging_code_geo
      t.text :cities
      t.text :cities_tags
      t.text :purchase_places
      t.text :stores
      t.text :countries
      t.text :countries_tags
      t.text :countries_fr
      t.text :ingredients_text
      t.text :traces
      t.text :traces_tags
      t.string :serving_size
      t.string :no_nutriments
      t.integer :additives_n
      t.text :additives
      t.text :additives_tags
      t.integer :ingredients_from_palm_oil_n
      t.text :ingredients_from_palm_oil
      t.text :ingredients_from_palm_oil_tags
      t.integer :ingredients_that_may_be_from_palm_oil_n
      t.text :ingredients_that_may_be_from_palm_oil
      t.text :ingredients_that_may_be_from_palm_oil_tags
      t.string :nutrition_grade_fr
      t.string :main_category
      t.string :main_category_fr
      t.text :image_url
      t.text :image_small_url
      t.decimal :energy_100g
      t.decimal :energy_kj_100g
      t.decimal :energy_kcal_100g
      t.decimal :proteins_100g
      t.decimal :casein_100g
      t.decimal :serum_proteins_100g
      t.decimal :nucleotides_100g
      t.decimal :carbohydrates_100g
      t.decimal :sugars_100g
      t.decimal :sucrose_100g
      t.decimal :glucose_100g
      t.decimal :fructose_100g
      t.decimal :lactose_100g
      t.decimal :maltose_100g
      t.decimal :maltodextrins_100g
      t.decimal :starch_100g
      t.decimal :polyols_100g
      t.decimal :fat_100g
      t.decimal :saturated_fat_100g
      t.decimal :butyric_acid_100g
      t.decimal :caproic_acid_100g
      t.decimal :caprylic_acid_100g
      t.decimal :capric_acid_100g
      t.decimal :lauric_acid_100g
      t.decimal :myristic_acid_100g
      t.decimal :palmitic_acid_100g
      t.decimal :stearic_acid_100g
      t.decimal :arachidic_acid_100g
      t.decimal :behenic_acid_100g
      t.decimal :lignoceric_acid_100g
      t.decimal :cerotic_acid_100g
      t.decimal :montanic_acid_100g
      t.decimal :melissic_acid_100g
      t.decimal :monounsaturated_fat_100g
      t.decimal :polyunsaturated_fat_100g
      t.decimal :omega_3_fat_100g
      t.decimal :alpha_linolenic_acid_100g
      t.decimal :eicosapentaenoic_acid_100g
      t.decimal :docosahexaenoic_acid_100g
      t.decimal :omega_6_fat_100g
      t.decimal :linoleic_acid_100g
      t.decimal :arachidonic_acid_100g
      t.decimal :gamma_linolenic_acid_100g
      t.decimal :dihomo_gamma_linolenic_acid_100g
      t.decimal :omega_9_fat_100g
      t.decimal :oleic_acid_100g
      t.decimal :elaidic_acid_100g
      t.decimal :gondoic_acid_100g
      t.decimal :mead_acid_100g
      t.decimal :erucic_acid_100g
      t.decimal :nervonic_acid_100g
      t.decimal :trans_fat_100g
      t.decimal :cholesterol_100g
      t.decimal :fiber_100g
      t.decimal :sodium_100g
      t.decimal :alcohol_100g
      t.decimal :vitamin_a_100g
      t.decimal :vitamin_d_100g
      t.decimal :vitamin_e_100g
      t.decimal :vitamin_k_100g
      t.decimal :vitamin_c_100g
      t.decimal :vitamin_b1_100g
      t.decimal :vitamin_b2_100g
      t.decimal :vitamin_pp_100g
      t.decimal :vitamin_b6_100g
      t.decimal :vitamin_b9_100g
      t.decimal :vitamin_b12_100g
      t.decimal :biotin_100g
      t.decimal :pantothenic_acid_100g
      t.decimal :silica_100g
      t.decimal :bicarbonate_100g
      t.decimal :potassium_100g
      t.decimal :chloride_100g
      t.decimal :calcium_100g
      t.decimal :phosphorus_100g
      t.decimal :iron_100g
      t.decimal :magnesium_100g
      t.decimal :zinc_100g
      t.decimal :copper_100g
      t.decimal :manganese_100g
      t.decimal :fluoride_100g
      t.decimal :selenium_100g
      t.decimal :chromium_100g
      t.decimal :molybdenum_100g
      t.decimal :iodine_100g
      t.decimal :caffeine_100g
      t.decimal :taurine_100g
      t.decimal :ph_100g
      t.decimal :fruits_vegetables_nuts_100g
      t.decimal :carbon_footprint_100g
      t.decimal :nutrition_score_fr_100g
      t.decimal :nutrition_score_uk_100g

      t.timestamps
    end
    add_index :products, :code
  end
end
